### ISSUE TITLE
IsShownOnScreen() assert failing

### ISSUE THREAD

**Issue by Niujk** [gerddie/ginkgocadx#28] opened 2017-02-08 08:54 UTC
Trying to open a DICOM file using the [trusty main PPA version](https://launchpad.net/~gert-die/+archive/ubuntu/ginkgocadx-trusty) I got this [error message](https://cloud.githubusercontent.com/assets/7169204/22729514/58bd1138-ede3-11e6-9b81-0ad3f23c81b5.png):
>../src/common/glcmn.cpp(59): assert "IsShownOnScreen()" failed in SetCurrent(): can't make hidden GL canvas current

Assert backtrace [here](https://github.com/gerddie/ginkgocadx/files/760133/assert.txt).

Then, inside the application, ['series' preview](https://cloud.githubusercontent.com/assets/7169204/22729428/f786c6c0-ede2-11e6-88a3-a78599f1ace9.png) on the left side are buggy.

**Comment by gerddie** [comment] 2017-02-08 12:51
I was able to reproduce the assertion fault, but it was within a virtual machine that uses the Virtualbox video driver which doesn't seem to implement the required extensions, end hence, OpenGL is not properly set up and creating the OpenGL context fails or is incomplete. The buggy display of the output is probably a fall-out of this problem.

When you run the program from a terminal do you see any OpenGL related error messages?

**Comment by Niujk** [comment] 2017-02-08 13:44
I will test that tomorrow (I'm half-time employed) and will report back editing here. Thanks.

Edit: Tried opening from console/terminal. Getting the exact same issues. No extra OpenGL related error messages so far.

**Comment by gerddie** [comment] 2017-02-09 10:57
Could you post the output on the terminal and the output of the command **glxinfo** (If not available it is in the **mesa-utils** package).

**Comment by Niujk** [comment] 2017-02-09 11:09
- ginkgocad output

```
us-pal-prv@PC-PAL-PRV:/bin$ sudo ginkgocadx 
[sudo] password for us-pal-prv: 
calling InitWX(argc, argv);
12:01:34: Debug: User config file: /home/us-pal-prv/.GinkgoUser
12:01:34: Debug: Global config file: /usr/bin/ginkgocadx.ini
12:01:34: Debug: Machine config file: /usr/bin/GinkgoMachine.ini
I: Starting Ginkgo CADx 3.8.4 32 bits

(ginkgocadx:7911): IBUS-WARNING **: The owner of /home/us-pal-prv/.config/ibus/bus is not root!
12:01:34: Debug: pTopLevel:isMaximized=1
12:01:34: Debug: Set windows size:(0, 0)
../src/common/glcmn.cpp(59): assert "IsShownOnScreen()" failed in SetCurrent(): can't make hidden GL canvas current
```

- glxinfo output - [download](https://github.com/gerddie/ginkgocadx/files/763449/glxinfo.txt)

**Comment by gerddie** [comment] 2017-02-09 11:11
Why do you sudo? What happens when you run it as normal user?

**Comment by Niujk** [comment] 2017-02-09 11:12
Oh, I'm just used to it. Outputs with and without sudo are exactly the same (if we ignore the "IBUS-WARNING about root not being the owner, ofc).
```us-pal-prv@PC-PAL-PRV:/bin$ ginkgocadx 
calling InitWX(argc, argv);
12:12:33: Debug: User config file: /home/us-pal-prv/.GinkgoUser
12:12:33: Debug: Global config file: /usr/bin/ginkgocadx.ini
12:12:33: Debug: Machine config file: /usr/bin/GinkgoMachine.ini
I: Starting Ginkgo CADx 3.8.4 32 bits
12:12:33: Debug: pTopLevel:isMaximized=1
12:12:33: Debug: Set windows size:(0, 0)
../src/common/glcmn.cpp(59): assert "IsShownOnScreen()" failed in SetCurrent(): can't make hidden GL canvas current
```

**Comment by gerddie** [comment] 2017-02-09 12:03
Well, as a general Unix hint for  security reasons you should only sudo if really needed.  

As for the bug, it seems that the bug seems to stem from the fact that on Trusty wxWidgets is in version 3.0.0, and there the assertion is used, but actually too tight as discussed [here](http://trac.wxwidgets.org/ticket/16193). 

Since I have trusty only in a virtual machine, I can not really test this because of other  errors, but there is a build of wxWidgets 3.0.2 available that you should be able to install, and this should replace the old wx libraries with the new ones.  Just add [this ppa](https://launchpad.net/~nickoe/+archive/ubuntu/wx3.0) and run *apt-get update; apt-get upgrade* and you should get version 3.0.2, 

If this solves your problem, then please close the issue.

**Comment by gerddie** [comment] 2017-02-10 06:45
Actually, I've copied the wxWidgets packages over to the ginkgocadx packport PPA and updated ginkgocadx to force the dependency on this newer version. So a simple *apt update; apt upgrade* should give you the new version.

**Comment by Niujk** [comment] 2017-02-10 08:27
Okay, assert error is solved. I am able to enter Ginkgo CADx v3.8.4 with no prompts.

Series preview are still buggy. Should I close this issue and open a new one about that?
Edit: I do that, seems the most reasonable thing.

Cheers.

**Closed as completed** 2017-02-10 08:29 UTC
